version: "3.8"

services:
  db:
    container_name: mariadb_container
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${ROOT_PASSWORD}
    networks:
      network:
        ipv4_address: 172.15.0.2
    ports:
      - "11445:3306"
    volumes:
      - ${DB_LOCATION}:/var/lib/mysql

networks:
  network:
    ipam:
      config:
        - subnet: 172.15.0.1/16
