version: "3.8"

services:
  app:
    container_name: jupyter_spark
    image: jupyter/pyspark-notebook
    restart: always
    networks:
      network:
        ipv4_address: 172.16.0.2
    ports:
      - "10010:8888"
      - "10011:4040"
    volumes:
      - "${WORK_DIR}:/home/jovyan/work"

networks:
  network:
    ipam:
      config:
        - subnet: 172.16.0.1/16
