version: '3.8'

services:
  zeppelin:
    container_name: apache_zeppelin
    image: apache/zeppelin:0.10.0
    restart: always
    networks:
      zeppelin-network:
        ipv4_address: 172.33.128.1
    ports:
      - "10000:8080"
    volumes:
      - ./zeppelin/notebook:/opt/zeppelin/notebook
      - ./zeppelin/conf:/opt/zeppelin/conf
      

networks:
  zeppelin-network:
    ipam:
      config:
        - subnet: 172.33.0.0/16
